/*
 * Waiting List Api
 *
 * Ambulance Waiting List management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: <your_email>
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ambulance_wl

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

type AmbulanceConditionsAPI interface {

	// internal registration of api routes
	addRoutes(routerGroup *gin.RouterGroup)

	// CreateCondition - Creates new condition for specified ambulance
	CreateCondition(ctx *gin.Context)

	// DeleteCondition - Deletes specific condition entry
	DeleteCondition(ctx *gin.Context)

	// GetConditions - Provides the list of conditions associated with ambulance
	GetConditions(ctx *gin.Context)

	// UpdateCondition - Updates specific condition entry
	UpdateCondition(ctx *gin.Context)
}

// partial implementation of AmbulanceConditionsAPI - all functions must be implemented in add on files
type implAmbulanceConditionsAPI struct {
}

func newAmbulanceConditionsAPI() AmbulanceConditionsAPI {
	return &implAmbulanceConditionsAPI{}
}

func (this *implAmbulanceConditionsAPI) addRoutes(routerGroup *gin.RouterGroup) {
	routerGroup.Handle(http.MethodPost, "/waiting-list/:ambulanceId/condition", this.CreateCondition)
	routerGroup.Handle(http.MethodDelete, "/waiting-list/:ambulanceId/condition/:conditionId", this.DeleteCondition)
	routerGroup.Handle(http.MethodGet, "/waiting-list/:ambulanceId/condition", this.GetConditions)
	routerGroup.Handle(http.MethodPut, "/waiting-list/:ambulanceId/condition/:conditionId", this.UpdateCondition)
}

// Copy following section to separate file, uncomment, and implement accordingly
// // CreateCondition - Creates new condition for specified ambulance
// func (this *implAmbulanceConditionsAPI) CreateCondition(ctx *gin.Context) {
// 	ctx.AbortWithStatus(http.StatusNotImplemented)
// }

// // DeleteCondition - Deletes specific condition entry
// func (this *implAmbulanceConditionsAPI) DeleteCondition(ctx *gin.Context) {
// 	ctx.AbortWithStatus(http.StatusNotImplemented)
// }

// // GetConditions - Provides the list of conditions associated with ambulance
//
//	func (this *implAmbulanceConditionsAPI) GetConditions(ctx *gin.Context) {
//	 	ctx.AbortWithStatus(http.StatusNotImplemented)
//	}
//
// UpdateCondition - Updates specific condition entry
// func (this *implAmbulanceConditionsAPI) UpdateCondition(ctx *gin.Context) {
// 	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//
